name: demo_kiewit_dbt
version: "1.0.0"
config-version: 2

profile: demo_kiewit_dbt

model-paths:
  - models
seed-paths:
  - seeds
test-paths:
  - tests
analysis-paths:
  - analyses
macro-paths:
  - macros
snapshot-paths:
  - snapshots

target-path: target
clean-targets:
  - target
  - dbt_packages

seeds:
  demo_kiewit_dbt:
    customer:
      +database: CUSTOMERS_DB
      +schema: lz
      +quote_columns: false
      +column_types:
        id: varchar(36)
        name: varchar(100)

models:
  demo_kiewit_dbt:
    lz:
      +database: CUSTOMERS_DB
      +schema: lz
      +materialized: incremental
      +tags:
        - lz
        - bronze
    staging:
      +database: CUSTOMERS_DB
      +schema: staging
      +materialized: table
      +tags:
        - staging
        - silver
    dbo:
      +database: CUSTOMERS_DB
      +schema: dbo
      +materialized: incremental
      +transient: false
      +tags:
        - dbo
        - gold