models:
  demo_kiewit_dbt:
    lz:
      +database:     CUSTOMERS_DB
      +schema:       lz
      +materialized: incremental
      +tags:         ["lz", "bronze"]
    staging:
      +database:     CUSTOMERS_DB
      +schema:       staging
      +materialized: table
      +tags:         ["staging", "silver"]
    dbo:
      +database:     CUSTOMERS_DB
      +schema:       dbo
      +materialized: incremental
      +transient:    false
      +tags:         ["dbo", "gold"]
