demo_kiewit_dbt:
  target: dev
  outputs:
    dev:
      type:      snowflake
      account:   "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user:      DAGSTER_DBT_USER
      password:  "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role:      DAGSTER_DBT_ROLE
      database:  CUSTOMERS_DB
      warehouse: COMPUTE_WH
      schema:    DEV_TUSHAR
      threads:   4
      client_session_keep_alive: false
    prod:
      type:      snowflake
      account:   "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user:      DAGSTER_DBT_USER
      password:  "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role:      DAGSTER_DBT_ROLE
      database:  CUSTOMERS_DB
      warehouse: COMPUTE_WH
      schema:    dbo
      threads:   4
      client_session_keep_alive: false