version: 2

seeds:
  - name: customer
    description: "Raw CSV seed — UUID id + customer name"
    columns:
      - name: id
        tests: [not_null, unique]
      - name: name
        tests: [not_null]

models:
  - name: lz_customers
    description: "Bronze — CUSTOMERS_DB.LZ.LZ_CUSTOMERS"
    columns:
      - name: customer_id
        tests: [not_null]

  - name: stg_customers
    description: "Silver — CUSTOMERS_DB.STAGING.STG_CUSTOMERS"
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: full_name
        tests: [not_null]
      - name: first_name
        tests: [not_null]
      - name: last_name
        tests: [not_null]

  - name: dbo_customers
    description: "Gold — CUSTOMERS_DB.DBO.DBO_CUSTOMERS"
    columns:
      - name: customer_id
        tests: [not_null, unique]